/-
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
Original development: Formalization Worker A
-/
module

public import ContinuousGroupCohomology.TopologicalQuotientConjugationAction

/-!
# Closed topological coinvariants

This file defines the closed topological coinvariants of a commutative
topological group `A` under an action of a group `G` by pointwise continuous
automorphisms.  They are the quotient of `A` by the topological closure of the
subgroup generated by the differences `g • a * a⁻¹`.

Only the individual action maps are assumed continuous.  No topology on `G`
and no joint continuity assertion is used.  The quotient carries mathlib's
honest quotient topology, and its canonical projection is continuous.

The algebraic coinvariants are retained as the quotient by the unclosed
difference subgroup.  There is a canonical continuous comparison from them
to the closed topological coinvariants; the two are not identified unless the
algebraic relation subgroup is proved closed.
-/

set_option warningAsError true

@[expose] public section

noncomputable section

universe uG uA uB uC uN uE uQ uE'

/-- An action by multiplicative automorphisms whose individual values are
continuous.  The acting group carries no topology, and this structure makes no
joint-continuity claim. -/
structure PointwiseContinuousMulAction (G : Type uG) (A : Type uA)
    [Group G] [Group A] [TopologicalSpace A] where
  /-- The underlying algebraic action. -/
  toMonoidHom : G →* MulAut A
  /-- Each action value is continuous. -/
  continuous_toFun : ∀ g : G, Continuous (toMonoidHom g)

namespace PointwiseContinuousMulAction

variable {G : Type uG} {A : Type uA}
  [Group G] [Group A] [TopologicalSpace A]

instance instCoeFun : CoeFun (PointwiseContinuousMulAction G A) (fun _ => G → A → A) :=
  ⟨fun ρ g ↦ ρ.toMonoidHom g⟩

@[ext]
theorem ext {ρ σ : PointwiseContinuousMulAction G A}
    (h : ρ.toMonoidHom = σ.toMonoidHom) : ρ = σ := by
  cases ρ
  cases σ
  cases h
  rfl

@[simp]
theorem map_one (ρ : PointwiseContinuousMulAction G A) (a : A) : ρ 1 a = a := by
  exact DFunLike.congr_fun (_root_.map_one ρ.toMonoidHom) a

@[simp]
theorem map_mul (ρ : PointwiseContinuousMulAction G A) (g h : G) (a : A) :
    ρ (g * h) a = ρ g (ρ h a) := by
  exact DFunLike.congr_fun (_root_.map_mul ρ.toMonoidHom g h) a

/-- An individual action value, bundled as a continuous multiplicative
equivalence. -/
def continuousMulEquiv (ρ : PointwiseContinuousMulAction G A) (g : G) : A ≃ₜ* A where
  toMulEquiv := ρ.toMonoidHom g
  continuous_toFun := ρ.continuous_toFun g
  continuous_invFun := by
    have h : (ρ.toMonoidHom g).invFun = ρ.toMonoidHom g⁻¹ := by
      funext a
      have ha := DFunLike.congr_fun (map_inv ρ.toMonoidHom g) a
      exact ha.symm
    rw [h]
    exact ρ.continuous_toFun g⁻¹

@[simp]
theorem continuousMulEquiv_apply (ρ : PointwiseContinuousMulAction G A)
    (g : G) (a : A) : ρ.continuousMulEquiv g a = ρ g a := rfl

/-- The trivial pointwise continuous action. -/
def trivial : PointwiseContinuousMulAction G A where
  toMonoidHom := 1
  continuous_toFun := fun _ ↦ continuous_id

@[simp]
theorem trivial_apply (g : G) (a : A) :
    (trivial : PointwiseContinuousMulAction G A) g a = a := rfl

end PointwiseContinuousMulAction

namespace PointwiseContinuousMulAction

variable {G : Type uG} {A : Type uA}
  [Group G] [CommGroup A] [TopologicalSpace A] [IsTopologicalGroup A]

/-- The set of action differences `g • a * a⁻¹`. -/
def differenceSet (ρ : PointwiseContinuousMulAction G A) : Set A :=
  {x | ∃ (g : G) (a : A), x = ρ g a * a⁻¹}

/-- The algebraic subgroup generated by all action differences. -/
def differenceSubgroup (ρ : PointwiseContinuousMulAction G A) : Subgroup A :=
  Subgroup.closure (ρ.differenceSet)

/-- The closed subgroup generated by all action differences. -/
def closedDifferenceSubgroup (ρ : PointwiseContinuousMulAction G A) : Subgroup A :=
  (ρ.differenceSubgroup).topologicalClosure

instance instNormalDifferenceSubgroup (ρ : PointwiseContinuousMulAction G A) :
    (ρ.differenceSubgroup).Normal :=
  Subgroup.normal_of_isMulCommutative _

instance instNormalClosedDifferenceSubgroup (ρ : PointwiseContinuousMulAction G A) :
    (ρ.closedDifferenceSubgroup).Normal :=
  Subgroup.normal_of_isMulCommutative _

/-- Underlying algebraic coinvariants: quotient by the unclosed relation
subgroup. -/
abbrev AlgebraicCoinvariants (ρ : PointwiseContinuousMulAction G A) :=
  A ⧸ ρ.differenceSubgroup

/-- Closed topological coinvariants, carrying mathlib's quotient topology. -/
abbrev Coinvariants (ρ : PointwiseContinuousMulAction G A) :=
  A ⧸ ρ.closedDifferenceSubgroup

/-- The canonical continuous projection to closed topological coinvariants. -/
def coinvariantsMk (ρ : PointwiseContinuousMulAction G A) :
    A →ₜ* ρ.Coinvariants where
  toMonoidHom := QuotientGroup.mk' ρ.closedDifferenceSubgroup
  continuous_toFun := QuotientGroup.continuous_mk

@[simp]
theorem coinvariantsMk_apply (ρ : PointwiseContinuousMulAction G A) (a : A) :
    ρ.coinvariantsMk a = QuotientGroup.mk a := rfl

omit [IsTopologicalGroup A] in
/-- Each action difference belongs to the algebraic relation subgroup. -/
theorem difference_mem_differenceSubgroup
    (ρ : PointwiseContinuousMulAction G A) (g : G) (a : A) :
    ρ g a * a⁻¹ ∈ ρ.differenceSubgroup :=
  Subgroup.subset_closure ⟨g, a, rfl⟩

/-- The projection identifies an element with each of its translates.  This
also fixes the action-difference orientation used by the construction. -/
@[simp]
theorem coinvariantsMk_action (ρ : PointwiseContinuousMulAction G A) (g : G) (a : A) :
    ρ.coinvariantsMk (ρ g a) = ρ.coinvariantsMk a := by
  apply QuotientGroup.eq_iff_div_mem.mpr
  simpa only [closedDifferenceSubgroup, div_eq_mul_inv] using
    Subgroup.le_topologicalClosure ρ.differenceSubgroup
      (ρ.difference_mem_differenceSubgroup g a)

/-- The algebraic quotient projection. -/
def algebraicMk (ρ : PointwiseContinuousMulAction G A) :
    A →ₜ* ρ.AlgebraicCoinvariants where
  toMonoidHom := QuotientGroup.mk' ρ.differenceSubgroup
  continuous_toFun := QuotientGroup.continuous_mk

/-- Canonical comparison from algebraic coinvariants to closed topological
coinvariants.  It is generally a further quotient, not an equivalence. -/
def algebraicToClosed (ρ : PointwiseContinuousMulAction G A) :
    ρ.AlgebraicCoinvariants →ₜ* ρ.Coinvariants where
  toMonoidHom := QuotientGroup.lift ρ.differenceSubgroup ρ.coinvariantsMk
    (fun x hx ↦ QuotientGroup.eq_one_iff x |>.mpr
      (Subgroup.le_topologicalClosure ρ.differenceSubgroup hx))
  continuous_toFun := by
    rw [(QuotientGroup.isQuotientMap_mk ρ.differenceSubgroup).continuous_iff]
    exact ρ.coinvariantsMk.continuous

@[simp]
theorem algebraicToClosed_algebraicMk
    (ρ : PointwiseContinuousMulAction G A) (a : A) :
    ρ.algebraicToClosed (ρ.algebraicMk a) = ρ.coinvariantsMk a := rfl

theorem algebraicToClosed_surjective
    (ρ : PointwiseContinuousMulAction G A) :
    Function.Surjective ρ.algebraicToClosed := by
  intro x
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  exact ⟨ρ.algebraicMk a, rfl⟩

/-- If the algebraic relation subgroup is already closed, taking its closure
does not enlarge it. -/
theorem closedDifferenceSubgroup_eq_differenceSubgroup
    (ρ : PointwiseContinuousMulAction G A)
    (hρ : IsClosed (ρ.differenceSubgroup : Set A)) :
    ρ.closedDifferenceSubgroup = ρ.differenceSubgroup :=
  le_antisymm
    (Subgroup.topologicalClosure_minimal ρ.differenceSubgroup le_rfl hρ)
    (Subgroup.le_topologicalClosure ρ.differenceSubgroup)

/-- A homomorphism kills every action difference precisely in the pointwise
form useful for the universal property. -/
def KillsDifferences {B : Type uB} [Group B]
    (ρ : PointwiseContinuousMulAction G A) (f : A → B) : Prop :=
  ∀ (g : G) (a : A), f (ρ g a * a⁻¹) = 1

omit [IsTopologicalGroup A] in
/-- Killing the generators kills their algebraic closure. -/
theorem differenceSubgroup_le_ker {B : Type uB} [Group B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →* B)
    (hf : ρ.KillsDifferences f) : ρ.differenceSubgroup ≤ f.ker := by
  rw [differenceSubgroup, Subgroup.closure_le]
  rintro x ⟨g, a, rfl⟩
  exact hf g a

/-- Algebraic universal property, bundled continuously for the quotient
topology: a continuous homomorphism killing every action difference factors
through the unclosed algebraic coinvariants. -/
def algebraicLift {B : Type uB} [Group B] [TopologicalSpace B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.KillsDifferences f) : ρ.AlgebraicCoinvariants →ₜ* B where
  toMonoidHom := QuotientGroup.lift ρ.differenceSubgroup f
    (ρ.differenceSubgroup_le_ker f.toMonoidHom hf)
  continuous_toFun := by
    rw [(QuotientGroup.isQuotientMap_mk ρ.differenceSubgroup).continuous_iff]
    exact f.continuous

omit [IsTopologicalGroup A] in
@[simp]
theorem algebraicLift_algebraicMk
    {B : Type uB} [Group B] [TopologicalSpace B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.KillsDifferences f) (a : A) :
    ρ.algebraicLift f hf (ρ.algebraicMk a) = f a := rfl

omit [IsTopologicalGroup A] in
/-- Continuous homomorphisms out of the algebraic coinvariants are determined
on the canonical projection. -/
theorem algebraicHom_ext {B : Type uB} [Group B] [TopologicalSpace B]
    (ρ : PointwiseContinuousMulAction G A)
    {f f' : ρ.AlgebraicCoinvariants →ₜ* B}
    (h : f.comp ρ.algebraicMk = f'.comp ρ.algebraicMk) : f = f' := by
  apply ContinuousMonoidHom.ext
  intro x
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  exact DFunLike.congr_fun h a

/-- Raw topological universal property.  Without a separation assumption on
the target, the exact condition is that `f` kill the closed relation subgroup. -/
def liftOfClosed {B : Type uB} [Group B] [TopologicalSpace B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.closedDifferenceSubgroup ≤ f.ker) : ρ.Coinvariants →ₜ* B where
  toMonoidHom := QuotientGroup.lift ρ.closedDifferenceSubgroup f hf
  continuous_toFun := by
    rw [(QuotientGroup.isQuotientMap_mk ρ.closedDifferenceSubgroup).continuous_iff]
    exact f.continuous

@[simp]
theorem liftOfClosed_mk {B : Type uB} [Group B] [TopologicalSpace B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.closedDifferenceSubgroup ≤ f.ker) (a : A) :
    ρ.liftOfClosed f hf (ρ.coinvariantsMk a) = f a := rfl

/-- A continuous homomorphism to a T1 group which kills every action
difference kills their closed generated subgroup.  The T1 assumption makes
the target kernel closed; no separation hypothesis is imposed on `A` or `G`. -/
theorem closedDifferenceSubgroup_le_ker {B : Type uB}
    [Group B] [TopologicalSpace B] [T1Space B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.KillsDifferences f) :
      ρ.closedDifferenceSubgroup ≤ f.ker := by
  apply Subgroup.topologicalClosure_minimal
  · exact ρ.differenceSubgroup_le_ker f.toMonoidHom hf
  · exact isClosed_singleton.preimage f.continuous

/-- Topological universal property for continuous homomorphisms to T1 groups
which kill every action difference. -/
def lift {B : Type uB} [Group B] [TopologicalSpace B] [T1Space B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.KillsDifferences f) : ρ.Coinvariants →ₜ* B :=
  ρ.liftOfClosed f (ρ.closedDifferenceSubgroup_le_ker f hf)

@[simp]
theorem lift_mk {B : Type uB} [Group B] [TopologicalSpace B] [T1Space B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.KillsDifferences f) (a : A) :
    ρ.lift f hf (ρ.coinvariantsMk a) = f a := rfl

/-- The algebraic universal factorization agrees with the closed one through
the canonical algebraic-to-closed comparison whenever the T1 lift is
available. -/
theorem algebraicLift_eq_lift_comp
    {B : Type uB} [Group B] [TopologicalSpace B] [T1Space B]
    (ρ : PointwiseContinuousMulAction G A) (f : A →ₜ* B)
    (hf : ρ.KillsDifferences f) :
    ρ.algebraicLift f hf = (ρ.lift f hf).comp ρ.algebraicToClosed := by
  apply ContinuousMonoidHom.ext
  intro x
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  change f a = f a
  rfl

theorem hom_ext {B : Type uB} [Group B] [TopologicalSpace B]
    (ρ : PointwiseContinuousMulAction G A) {f f' : ρ.Coinvariants →ₜ* B}
    (h : f.comp ρ.coinvariantsMk = f'.comp ρ.coinvariantsMk) : f = f' := by
  apply ContinuousMonoidHom.ext
  intro x
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  exact DFunLike.congr_fun h a

section Functoriality

variable {B : Type uB} {C : Type uC}
  [CommGroup B] [CommGroup C]
  [TopologicalSpace B] [TopologicalSpace C]
  [IsTopologicalGroup B] [IsTopologicalGroup C]

/-- Equivariance of a multiplicative homomorphism for two pointwise
continuous actions of the same group. -/
def IsEquivariant (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B) (f : A → B) : Prop :=
  ∀ (g : G) (a : A), f (ρ g a) = σ g (f a)

/-- A continuous equivariant homomorphism induces a continuous homomorphism
on closed topological coinvariants. -/
def map (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B) (f : A →ₜ* B)
    (hf : IsEquivariant ρ σ f) : ρ.Coinvariants →ₜ* σ.Coinvariants := by
  apply ρ.liftOfClosed (σ.coinvariantsMk.comp f)
  intro x hx
  change σ.coinvariantsMk (f x) = 1
  apply (QuotientGroup.eq_one_iff (f x)).mpr
  change x ∈ σ.closedDifferenceSubgroup.comap f.toMonoidHom
  apply (Subgroup.topologicalClosure_minimal ρ.differenceSubgroup ?_ ?_) hx
  · intro y hy
    have hy' := ρ.differenceSubgroup_le_ker
      ((σ.coinvariantsMk.comp f).toMonoidHom) (fun g a ↦ by
        change σ.coinvariantsMk (f (ρ g a * a⁻¹)) = 1
        rw [_root_.map_mul, map_inv, hf g a, _root_.map_mul, map_inv,
          σ.coinvariantsMk_action]
        simp) hy
    exact (QuotientGroup.eq_one_iff (f y)).mp hy'
  · change IsClosed (f ⁻¹' (σ.closedDifferenceSubgroup : Set B))
    exact σ.differenceSubgroup.isClosed_topologicalClosure.preimage
      f.continuous

@[simp]
theorem map_mk (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B) (f : A →ₜ* B)
    (hf : IsEquivariant ρ σ f) (a : A) :
    map ρ σ f hf (ρ.coinvariantsMk a) = σ.coinvariantsMk (f a) := by
  exact ρ.liftOfClosed_mk (σ.coinvariantsMk.comp f) _ a

omit [IsTopologicalGroup A] in
theorem isEquivariant_id (ρ : PointwiseContinuousMulAction G A) :
    IsEquivariant ρ ρ (ContinuousMonoidHom.id A) := by
  intro g a
  rfl

theorem map_id (ρ : PointwiseContinuousMulAction G A) :
    map ρ ρ (ContinuousMonoidHom.id A) ρ.isEquivariant_id =
      ContinuousMonoidHom.id ρ.Coinvariants := by
  apply ContinuousMonoidHom.ext
  intro x
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  change map ρ ρ (ContinuousMonoidHom.id A) ρ.isEquivariant_id
      (ρ.coinvariantsMk a) = ρ.coinvariantsMk a
  rw [map_mk]
  change ρ.coinvariantsMk a = ρ.coinvariantsMk a
  rfl

omit [IsTopologicalGroup A] [IsTopologicalGroup B] [IsTopologicalGroup C] in
/-- The composite of equivariant continuous homomorphisms is equivariant. -/
theorem isEquivariant_comp (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B)
    (τ : PointwiseContinuousMulAction G C)
    (f : A →ₜ* B) (g : B →ₜ* C)
    (hf : IsEquivariant ρ σ f) (hg : IsEquivariant σ τ g) :
    IsEquivariant ρ τ (g.comp f) := by
  intro q a
  change g (f (ρ q a)) = τ q (g (f a))
  rw [hf q a, hg q (f a)]

theorem map_comp (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B)
    (τ : PointwiseContinuousMulAction G C)
    (f : A →ₜ* B) (g : B →ₜ* C)
    (hf : IsEquivariant ρ σ f) (hg : IsEquivariant σ τ g) :
    map ρ τ (g.comp f) (isEquivariant_comp ρ σ τ f g hf hg) =
      (map σ τ g hg).comp (map ρ σ f hf) := by
  apply ContinuousMonoidHom.ext
  intro x
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  change map ρ τ (g.comp f) (isEquivariant_comp ρ σ τ f g hf hg)
      (ρ.coinvariantsMk a) =
    map σ τ g hg (map ρ σ f hf (ρ.coinvariantsMk a))
  rw [map_mk, map_mk, map_mk]
  change τ.coinvariantsMk (g (f a)) = τ.coinvariantsMk (g (f a))
  rfl

omit [IsTopologicalGroup A] [IsTopologicalGroup B] in
/-- Equivariance is preserved by taking the inverse of an equivariant
continuous multiplicative equivalence. -/
theorem isEquivariant_symm (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B) (e : A ≃ₜ* B)
    (he : IsEquivariant ρ σ e) : IsEquivariant σ ρ e.symm := by
  intro g b
  apply e.injective
  calc
    e (e.symm (σ g b)) = σ g b := e.apply_symm_apply _
    _ = σ g (e (e.symm b)) := by rw [e.apply_symm_apply]
    _ = e (ρ g (e.symm b)) := (he g (e.symm b)).symm

/-- A continuous equivariant equivalence induces a continuous equivalence on
closed topological coinvariants. -/
def congr (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B) (e : A ≃ₜ* B)
    (he : IsEquivariant ρ σ e) : ρ.Coinvariants ≃ₜ* σ.Coinvariants := by
  let ef : A →ₜ* B := {
    toMonoidHom := e.toMonoidHom
    continuous_toFun := e.continuous }
  let einf : B →ₜ* A := {
    toMonoidHom := e.symm.toMonoidHom
    continuous_toFun := e.symm.continuous }
  have hef : IsEquivariant ρ σ ef := he
  have heinf : IsEquivariant σ ρ einf := isEquivariant_symm ρ σ e he
  exact {
    toFun := map ρ σ ef hef
    invFun := map σ ρ einf heinf
    left_inv := fun x ↦ by
      obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
      change map σ ρ einf heinf
          (map ρ σ ef hef (ρ.coinvariantsMk a)) = ρ.coinvariantsMk a
      rw [map_mk, map_mk]
      exact congrArg ρ.coinvariantsMk (e.symm_apply_apply a)
    right_inv := fun x ↦ by
      obtain ⟨b, rfl⟩ := QuotientGroup.mk_surjective x
      change map ρ σ ef hef
          (map σ ρ einf heinf (σ.coinvariantsMk b)) = σ.coinvariantsMk b
      rw [map_mk, map_mk]
      exact congrArg σ.coinvariantsMk (e.apply_symm_apply b)
    map_mul' := (map ρ σ ef hef).map_mul
    continuous_toFun := (map ρ σ ef hef).continuous
    continuous_invFun := (map σ ρ einf heinf).continuous }

@[simp]
theorem congr_mk (ρ : PointwiseContinuousMulAction G A)
    (σ : PointwiseContinuousMulAction G B) (e : A ≃ₜ* B)
    (he : IsEquivariant ρ σ e) (a : A) :
    congr ρ σ e he (ρ.coinvariantsMk a) = σ.coinvariantsMk (e a) := by
  let ef : A →ₜ* B := {
    toMonoidHom := e.toMonoidHom
    continuous_toFun := e.continuous }
  have hef : IsEquivariant ρ σ ef := he
  change map ρ σ ef hef (ρ.coinvariantsMk a) = σ.coinvariantsMk (e a)
  rw [map_mk]
  rfl

end Functoriality

section TrivialAction

omit [IsTopologicalGroup A] in
/-- The algebraic relation subgroup of the trivial action is trivial. -/
@[simp]
theorem differenceSubgroup_trivial :
    differenceSubgroup
      (PointwiseContinuousMulAction.trivial : PointwiseContinuousMulAction G A) = ⊥ := by
  apply le_antisymm
  · rw [differenceSubgroup, Subgroup.closure_le]
    rintro x ⟨g, a, rfl⟩
    simp
  · exact bot_le

/-- Without a T1 hypothesis, trivial-action closed coinvariants quotient by
the closure of `{1}` rather than silently identifying that closure with `{1}`. -/
@[simp]
theorem closedDifferenceSubgroup_trivial :
    closedDifferenceSubgroup
      (PointwiseContinuousMulAction.trivial : PointwiseContinuousMulAction G A) =
      (⊥ : Subgroup A).topologicalClosure := by
  rw [closedDifferenceSubgroup, differenceSubgroup_trivial]

/-- For a T1 coefficient group, the closed relation subgroup of the trivial
action is trivial. -/
@[simp]
theorem closedDifferenceSubgroup_trivial_of_t1 [T1Space A] :
    closedDifferenceSubgroup
      (PointwiseContinuousMulAction.trivial : PointwiseContinuousMulAction G A) = ⊥ := by
  rw [closedDifferenceSubgroup_trivial]
  exact le_antisymm
    (Subgroup.topologicalClosure_minimal ⊥ le_rfl isClosed_singleton)
    bot_le

omit [IsTopologicalGroup A] in
/-- An action by a subsingleton acting group is algebraically trivial. -/
theorem differenceSubgroup_eq_bot_of_subsingleton [Subsingleton G]
    (ρ : PointwiseContinuousMulAction G A) : ρ.differenceSubgroup = ⊥ := by
  apply le_antisymm
  · rw [differenceSubgroup, Subgroup.closure_le]
    rintro x ⟨g, a, rfl⟩
    have hg : g = 1 := Subsingleton.elim _ _
    simp [hg]
  · exact bot_le

/-- For a T1 coefficient group, any action by a subsingleton acting group has
trivial closed relation subgroup. -/
@[simp]
theorem closedDifferenceSubgroup_eq_bot_of_subsingleton
    [Subsingleton G] [T1Space A]
    (ρ : PointwiseContinuousMulAction G A) :
    ρ.closedDifferenceSubgroup = ⊥ := by
  rw [closedDifferenceSubgroup, ρ.differenceSubgroup_eq_bot_of_subsingleton]
  exact le_antisymm
    (Subgroup.topologicalClosure_minimal ⊥ le_rfl isClosed_singleton)
    bot_le

end TrivialAction

end PointwiseContinuousMulAction

namespace ContinuousGroupExtension

variable {N : Type uN} {E : Type uE} {Q : Type uQ}
  [Group N] [Group E] [Group Q]
  [TopologicalSpace N] [TopologicalSpace E] [TopologicalSpace Q]
  [IsTopologicalGroup N] [IsTopologicalGroup E] [IsTopologicalGroup Q]

/-- The quotient conjugation action on topological abelianization, packaged as
a pointwise continuous action. -/
def quotientConjActTopologicalAbelianizationAction
    (S : ContinuousGroupExtension N E Q) :
    PointwiseContinuousMulAction Q (TopologicalAbelianization N) where
  toMonoidHom := S.quotientConjActTopologicalAbelianization
  continuous_toFun := fun q ↦
    (S.quotientConjActTopologicalAbelianizationContinuous q).continuous

/-- Closed topological coinvariants of the quotient conjugation action. -/
abbrev quotientConjActTopologicalAbelianizationCoinvariants
    (S : ContinuousGroupExtension N E Q) :=
  S.quotientConjActTopologicalAbelianizationAction.Coinvariants

/-- The canonical continuous projection from topological abelianization to
closed quotient-conjugation coinvariants. -/
def quotientConjActTopologicalAbelianizationCoinvariantsMk
    (S : ContinuousGroupExtension N E Q) :
    TopologicalAbelianization N →ₜ*
      S.quotientConjActTopologicalAbelianizationCoinvariants :=
  S.quotientConjActTopologicalAbelianizationAction.coinvariantsMk

/-- Arbitrary-lift formula: the coinvariant projection identifies a kernel
class with its conjugate by any chosen lift. -/
@[simp]
theorem quotientConjActTopologicalAbelianizationCoinvariantsMk_conjAct
    (S : ContinuousGroupExtension N E Q) (e : E) (n : N) :
    S.quotientConjActTopologicalAbelianizationCoinvariantsMk
        (QuotientGroup.mk (S.toGroupExtension.conjAct e n)) =
      S.quotientConjActTopologicalAbelianizationCoinvariantsMk
        (QuotientGroup.mk n) := by
  rw [← S.quotientConjActTopologicalAbelianizationContinuous_apply_mk e n]
  exact S.quotientConjActTopologicalAbelianizationAction.coinvariantsMk_action
    (S.rightHom e) (QuotientGroup.mk n)

/-- Lift independence remains explicit at the coinvariant projection. -/
theorem quotientConjActTopologicalAbelianizationCoinvariantsMk_conjAct_eq_of_rightHom_eq
    (S : ContinuousGroupExtension N E Q) {e e' : E}
    (h : S.rightHom e = S.rightHom e') (n : N) :
    S.quotientConjActTopologicalAbelianizationCoinvariantsMk
        (QuotientGroup.mk (S.toGroupExtension.conjAct e n)) =
      S.quotientConjActTopologicalAbelianizationCoinvariantsMk
        (QuotientGroup.mk (S.toGroupExtension.conjAct e' n)) := by
  rw [S.topologicalAbelianization_conjAct_eq_of_rightHom_eq h n]

namespace Equiv

variable {E' : Type uE'} [Group E'] [TopologicalSpace E'] [IsTopologicalGroup E']
  {S : ContinuousGroupExtension N E Q}
  {S' : ContinuousGroupExtension N E' Q}

/-- A continuous equivalence of extensions preserves the packaged quotient
action with the accepted fixed-kernel/fixed-quotient orientation. -/
theorem quotientConjActTopologicalAbelianizationAction (equiv : S.Equiv S') :
    S'.quotientConjActTopologicalAbelianizationAction =
      S.quotientConjActTopologicalAbelianizationAction := by
  apply PointwiseContinuousMulAction.ext
  exact equiv.quotientConjActTopologicalAbelianization

/-- The induced equivalence on closed coinvariants, in the accepted
source-to-target orientation of an extension equivalence. -/
def quotientConjActTopologicalAbelianizationCoinvariantsEquiv
    (equiv : S.Equiv S') :
    S.quotientConjActTopologicalAbelianizationCoinvariants ≃ₜ*
      S'.quotientConjActTopologicalAbelianizationCoinvariants :=
  PointwiseContinuousMulAction.congr
    S.quotientConjActTopologicalAbelianizationAction
    S'.quotientConjActTopologicalAbelianizationAction
    (ContinuousMulEquiv.refl (TopologicalAbelianization N)) (by
      intro q a
      rw [equiv.quotientConjActTopologicalAbelianizationAction]
      rfl)

@[simp]
theorem quotientConjActTopologicalAbelianizationCoinvariantsEquiv_mk
    (equiv : S.Equiv S') (a : TopologicalAbelianization N) :
    equiv.quotientConjActTopologicalAbelianizationCoinvariantsEquiv
        (S.quotientConjActTopologicalAbelianizationCoinvariantsMk a) =
      S'.quotientConjActTopologicalAbelianizationCoinvariantsMk a :=
  PointwiseContinuousMulAction.congr_mk _ _ _ _ a

end Equiv

end ContinuousGroupExtension
