/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import ContinuousGroupCohomology.ProfiniteCoinducedRestriction
public import CGCExamples.TopRepDiscrete.SignAction
public import Mathlib.GroupTheory.Perm.Sign

/-!
# A nonnormal, nontrivial-coefficient boundary for twisted restriction

In the six-element permutation group, the subgroup generated by a
transposition is not normal. Restricting the integer sign representation to
it moves the constant-one (hence nonzero constant) function in `C(G/H, ℤ)`.
These witness facts are proved independently of the section-dependent restriction iso;
a downstream calculation applies the iso to the same point mass.
The finite example tests the nonnormal orientation and coefficient action;
finite groups alone cannot establish the theorem for closed nonopen subgroups.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option warningAsError true

@[expose] public section

namespace CGCExamples

/-- The six-element permutation group used for the nonnormal test. -/
abbrev ThreePerm := Equiv.Perm (Fin 3)

instance : TopologicalSpace ThreePerm := ⊥
instance : DiscreteTopology ThreePerm := discreteTopology_bot _

/-- The order-two subgroup of `S₃` generated by swapping `0` and `1`. -/
def transpositionSubgroup : Subgroup ThreePerm where
  carrier := {g | g = 1 ∨ g = Equiv.swap (0 : Fin 3) 1}
  one_mem' := Or.inl rfl
  mul_mem' := by
    intro g h hg hh
    rcases hg with rfl | rfl <;> rcases hh with rfl | rfl
    · exact Or.inl (one_mul _)
    · exact Or.inr (one_mul _)
    · exact Or.inr (mul_one _)
    · exact Or.inl (Equiv.swap_mul_self 0 1)
  inv_mem' := by
    intro g hg
    rcases hg with rfl | rfl
    · exact Or.inl (inv_one)
    · exact Or.inr (Equiv.swap_inv 0 1)

instance : IsClosed (transpositionSubgroup : Set ThreePerm) :=
  ⟨isOpen_discrete _⟩

/-- The selected transposition is a member of the order-two subgroup. -/
def transpositionElement : transpositionSubgroup :=
  ⟨Equiv.swap (0 : Fin 3) 1, Or.inr rfl⟩

/-- This two-element subgroup is genuinely nonnormal in `S₃`. -/
theorem transpositionSubgroup_not_normal : ¬ transpositionSubgroup.Normal := by
  intro hn
  have hc := hn.conj_mem transpositionElement.val transpositionElement.property
    (Equiv.swap (1 : Fin 3) 2)
  change _ = 1 ∨ _ = Equiv.swap (0 : Fin 3) 1 at hc
  rcases hc with h | h
  · have : (Equiv.swap (1 : Fin 3) 2 * Equiv.swap (0 : Fin 3) 1 *
        (Equiv.swap (1 : Fin 3) 2)⁻¹ : ThreePerm) ≠ 1 := by decide
    exact this h
  · have : (Equiv.swap (1 : Fin 3) 2 * Equiv.swap (0 : Fin 3) 1 *
        (Equiv.swap (1 : Fin 3) 2)⁻¹ : ThreePerm) ≠
        Equiv.swap (0 : Fin 3) 1 := by decide
    exact this h

/-- Pull the existing integer-unit sign action back along permutation sign. -/
abbrev signedThreePerm : TopRep ℤ ThreePerm :=
  .of <| .ofMonoidHom
    (show ThreePerm →* (ℤ →L[ℤ] ℤ) from
      signedIntegers.ρ.toMonoidHom.comp (Equiv.Perm.sign : ThreePerm →* ℤˣ))

/-- The chosen transposition negates a nonzero integer. -/
theorem signedThreePerm_transposition_one :
    signedThreePerm.ρ transpositionElement.val (1 : ℤ) = -1 := by
  change signedIntegers.ρ (Equiv.Perm.sign (Equiv.swap (0 : Fin 3) 1)) (1 : ℤ) = (-1 : ℤ)
  rw [Equiv.Perm.sign_swap (by decide : (0 : Fin 3) ≠ 1)]
  exact signedIntegers_negative_one

/-- The pointwise coefficient action cannot be replaced by a trivial action,
even on a constant function and a nonnormal subgroup. -/
theorem transposition_pointwise_constant (c : ThreePerm ⧸ transpositionSubgroup) :
    ((TopRep.pointwiseContinuousMap (ThreePerm ⧸ transpositionSubgroup)
        (TopRep.res transpositionSubgroup.subtype signedThreePerm)).ρ
      transpositionElement (ContinuousMap.const _ (1 : ℤ)) :
        C(ThreePerm ⧸ transpositionSubgroup, ℤ)) c = -1 := by
  rw [TopRep.pointwiseContinuousMap_ρ_apply]
  exact signedThreePerm_transposition_one

/-- A nonzero value is moved by the coefficient action. -/
theorem transposition_pointwise_constant_ne
    (c : ThreePerm ⧸ transpositionSubgroup) :
    ((TopRep.pointwiseContinuousMap (ThreePerm ⧸ transpositionSubgroup)
        (TopRep.res transpositionSubgroup.subtype signedThreePerm)).ρ
      transpositionElement (ContinuousMap.const _ (1 : ℤ)) :
        C(ThreePerm ⧸ transpositionSubgroup, ℤ)) c ≠ 1 := by
  rw [transposition_pointwise_constant]
  norm_num

/-- A left translate moves a left coset when the subgroup is nonnormal;
this rules out treating `G ⧸ H` as a trivial `G`-set. -/
theorem transposition_left_translate_moves_coset :
    (QuotientGroup.mk (transpositionElement.val * Equiv.swap (1 : Fin 3) 2) :
      ThreePerm ⧸ transpositionSubgroup) ≠
      QuotientGroup.mk (Equiv.swap (1 : Fin 3) 2) := by
  intro heq
  have hm := QuotientGroup.eq.mp heq.symm
  change (Equiv.swap (1 : Fin 3) 2)⁻¹ *
      (Equiv.swap (0 : Fin 3) 1 * Equiv.swap (1 : Fin 3) 2) = 1 ∨
    (Equiv.swap (1 : Fin 3) 2)⁻¹ *
      (Equiv.swap (0 : Fin 3) 1 * Equiv.swap (1 : Fin 3) 2) =
        Equiv.swap (0 : Fin 3) 1 at hm
  rcases hm with h | h
  · have : ((Equiv.swap (1 : Fin 3) 2)⁻¹ *
        (Equiv.swap (0 : Fin 3) 1 * Equiv.swap (1 : Fin 3) 2) : ThreePerm) ≠ 1 :=
      by decide
    exact this h
  · have : ((Equiv.swap (1 : Fin 3) 2)⁻¹ *
        (Equiv.swap (0 : Fin 3) 1 * Equiv.swap (1 : Fin 3) 2) : ThreePerm) ≠
          Equiv.swap (0 : Fin 3) 1 := by decide
    exact this h

/-- Inverting the left coset coordinate removes the effect of left translation
by the selected subgroup element, unlike the direct coset coordinate. -/
theorem transposition_inverse_coset_fixed :
    (QuotientGroup.mk ((transpositionElement.val * Equiv.swap (1 : Fin 3) 2)⁻¹) :
      ThreePerm ⧸ transpositionSubgroup) =
      QuotientGroup.mk ((Equiv.swap (1 : Fin 3) 2)⁻¹) := by
  apply QuotientGroup.eq.mpr
  simpa only [inv_inv, mul_assoc, mul_inv_cancel, mul_one] using
    transpositionElement.property

/-- The raw twisted coinduction action at the forward section coordinate is
negative, while forgetting the coefficient action would give the positive
value. The point mass is supported at the inverse of the chosen continuous
representative; no normalization of that representative is assumed. -/
theorem transposition_raw_forward_action (c : ThreePerm ⧸ transpositionSubgroup) :
    ∃ f : C(ThreePerm, ℤ),
      (QuotientGroup.mk (transpositionSubgroup.continuousCosetRepresentative c) :
        ThreePerm ⧸ transpositionSubgroup) = c ∧
      f ((transpositionSubgroup.continuousCosetRepresentative c)⁻¹) = 1 ∧
      f (transpositionElement.val *
          (transpositionSubgroup.continuousCosetRepresentative c)⁻¹) = 0 ∧
      signedThreePerm.ρ.coind₁ transpositionElement.val f
        (transpositionElement.val *
          (transpositionSubgroup.continuousCosetRepresentative c)⁻¹) = -1 := by
  let s := transpositionSubgroup.continuousCosetRepresentative
  let f : C(ThreePerm, ℤ) :=
    ⟨fun t => if t = (s c)⁻¹ then 1 else 0, continuous_of_discreteTopology⟩
  have hvalue : f ((s c)⁻¹) = 1 := by simp [f]
  refine ⟨f, transpositionSubgroup.continuousCosetRepresentative_mk c,
    hvalue, ?_, ?_⟩
  · have ha : (transpositionElement.val : ThreePerm) ≠ 1 := by decide
    have hne : transpositionElement.val * (s c)⁻¹ ≠ (s c)⁻¹ := by
      intro heq
      apply ha
      have heq' := congrArg (fun g : ThreePerm => g * s c) heq
      simpa only [mul_assoc, inv_mul_cancel, mul_one, one_mul] using heq'
    change (if transpositionElement.val * (s c)⁻¹ = (s c)⁻¹ then
      (1 : ℤ) else 0) = 0
    simp [hne]
  · rw [ContRepresentation.coind₁_apply_apply]
    have heval : f (transpositionElement.val⁻¹ *
        (transpositionElement.val * (s c)⁻¹)) = 1 := by
      simpa only [← mul_assoc, inv_mul_cancel, one_mul] using hvalue
    rw [heval]
    exact signedThreePerm_transposition_one

/-- The `H = ⊥` boundary has a nonzero coefficient value on every coset. -/
theorem bottom_pointwise_constant_one
    (c : ThreePerm ⧸ (⊥ : Subgroup ThreePerm)) :
    ((TopRep.pointwiseContinuousMap (ThreePerm ⧸ (⊥ : Subgroup ThreePerm))
        (TopRep.res (⊥ : Subgroup ThreePerm).subtype signedThreePerm)).ρ
      (1 : (⊥ : Subgroup ThreePerm)) (ContinuousMap.const _ (1 : ℤ)) :
        C(ThreePerm ⧸ (⊥ : Subgroup ThreePerm), ℤ)) c = 1 := by
  rw [TopRep.pointwiseContinuousMap_ρ_const]
  simp

/-- Even the `H = ⊤` boundary has a nontrivial pointwise sign action. -/
theorem top_pointwise_constant_neg_one
    (c : ThreePerm ⧸ (⊤ : Subgroup ThreePerm)) :
    ((TopRep.pointwiseContinuousMap (ThreePerm ⧸ (⊤ : Subgroup ThreePerm))
        (TopRep.res (⊤ : Subgroup ThreePerm).subtype signedThreePerm)).ρ
      (⟨transpositionElement.val, Subgroup.mem_top _⟩ : (⊤ : Subgroup ThreePerm))
      (ContinuousMap.const _ (1 : ℤ)) :
        C(ThreePerm ⧸ (⊤ : Subgroup ThreePerm), ℤ)) c = -1 := by
  rw [TopRep.pointwiseContinuousMap_ρ_const]
  exact signedThreePerm_transposition_one

/-- On the nonnormal signed example, the restriction iso sends a point mass to
distinct values at the identity and transposition, and sends its twisted
translate to a nonzero value at the transposition. -/
theorem transposition_profiniteCoind₁RestrictionIso_forward
    (c : ThreePerm ⧸ transpositionSubgroup) :
    ∃ f : C(ThreePerm, ℤ),
      ((TopRep.profiniteCoind₁RestrictionIso transpositionSubgroup signedThreePerm).hom).hom
        f (1 : transpositionSubgroup) c = 1 ∧
      ((TopRep.profiniteCoind₁RestrictionIso transpositionSubgroup signedThreePerm).hom).hom
        f transpositionElement c = 0 ∧
      ((TopRep.profiniteCoind₁RestrictionIso transpositionSubgroup signedThreePerm).hom).hom
        (signedThreePerm.ρ.coind₁ transpositionElement.val f)
        transpositionElement c = -1 := by
  obtain ⟨f, _, hone, hzero, hneg⟩ := transposition_raw_forward_action c
  refine ⟨f, ?_, ?_, ?_⟩
  · calc
      _ = f ((1 : transpositionSubgroup).val *
          (transpositionSubgroup.continuousCosetRepresentative c)⁻¹) :=
        TopRep.profiniteCoind₁RestrictionIso_hom_apply
          transpositionSubgroup signedThreePerm f (1 : transpositionSubgroup) c
      _ = 1 := by simpa only [Subgroup.coe_one, one_mul] using hone
  · exact (TopRep.profiniteCoind₁RestrictionIso_hom_apply
      transpositionSubgroup signedThreePerm f transpositionElement c).trans hzero
  · exact (TopRep.profiniteCoind₁RestrictionIso_hom_apply
      transpositionSubgroup signedThreePerm
        (signedThreePerm.ρ.coind₁ transpositionElement.val f) transpositionElement c).trans hneg

end CGCExamples
